version: 2

updates:
  # Github actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Python packages
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
