from __future__ import annotations

from typing import Any

COLOR_BGR2GRAY: int
COLOR_BGR2HSV: int
COLOR_GRAY2BGR: int
COLOR_HSV2BGR: int
COLOR_RGB2BGR: int
CHAIN_APPROX_SIMPLE: int
INTER_LANCZOS4: int
INTER_NEAREST: int
LINE_4: int
MORPH_CLOSE: int
MORPH_RECT: int
NORM_MINMAX: int
RETR_EXTERNAL: int
TM_CCORR_NORMED: int
WINDOW_NORMAL: int

def absdiff(src1: object, src2: object, *args: object, **kwargs: object) -> Any: ...
def approxPolyDP(curve: object, epsilon: float, closed: bool, *args: object, **kwargs: object) -> Any: ...
def arcLength(curve: object, closed: bool, *args: object, **kwargs: object) -> float: ...
def bilateralFilter(
    src: object, d: int, sigmaColor: float, sigmaSpace: float, *args: object, **kwargs: object
) -> Any: ...
def bitwise_and(src1: object, src2: object, *args: object, **kwargs: object) -> Any: ...
def bitwise_or(src1: object, src2: object, *args: object, **kwargs: object) -> Any: ...
def boundingRect(array: object, *args: object, **kwargs: object) -> tuple[int, int, int, int]: ...
def Canny(image: object, threshold1: float, threshold2: float, *args: object, **kwargs: object) -> Any: ...
def circle(
    img: object, center: tuple[int, int], radius: int, color: object, *args: object, **kwargs: object
) -> Any: ...
def contourArea(contour: object, *args: object, **kwargs: object) -> float: ...
def createTrackbar(trackbarName: str, windowName: str, value: int, count: int, onChange: object) -> None: ...
def cvtColor(src: object, code: int, *args: object, **kwargs: object) -> Any: ...
def destroyAllWindows() -> None: ...
def dilate(src: object, kernel: object, *args: object, **kwargs: object) -> Any: ...
def drawContours(
    image: object, contours: object, contourIdx: int, color: object, *args: object, **kwargs: object
) -> Any: ...
def erode(src: object, kernel: object, *args: object, **kwargs: object) -> Any: ...
def findContours(image: object, mode: int, method: int, *args: object, **kwargs: object) -> tuple[list[Any], Any]: ...
def getStructuringElement(shape: int, ksize: tuple[int, int], *args: object, **kwargs: object) -> Any: ...
def getTrackbarPos(trackbarname: str, winname: str) -> int: ...
def getWindowProperty(winname: str, prop_id: int) -> float: ...
def groupRectangles(
    rectList: object, groupThreshold: int, eps: float = ..., *args: object, **kwargs: object
) -> tuple[list[Any], Any]: ...
def imshow(winname: str, mat: object) -> None: ...
def imwrite(filename: str, img: object, *args: object, **kwargs: object) -> bool: ...
def inRange(src: object, lowerb: object, upperb: object, *args: object, **kwargs: object) -> Any: ...
def matchTemplate(image: object, templ: object, method: int, *args: object, **kwargs: object) -> Any: ...
def mean(src: object, *args: object, **kwargs: object) -> tuple[float, ...]: ...
def moments(array: object, *args: object, **kwargs: object) -> dict[str, float]: ...
def morphologyEx(src: object, op: int, kernel: object, *args: object, **kwargs: object) -> Any: ...
def namedWindow(winname: str, flags: int = ..., *args: object, **kwargs: object) -> None: ...
def normalize(
    src: object,
    dst: object,
    alpha: float = ...,
    beta: float = ...,
    norm_type: int = ...,
    *args: object,
    **kwargs: object,
) -> Any: ...
def pointPolygonTest(
    contour: object, pt: tuple[int, int], measureDist: bool, *args: object, **kwargs: object
) -> float: ...
def rectangle(
    img: object, pt1: tuple[int, int], pt2: tuple[int, int], color: object, *args: object, **kwargs: object
) -> Any: ...
def resize(src: object, dsize: tuple[int, int] | None, *args: object, **kwargs: object) -> Any: ...
def waitKey(delay: int = ..., *args: object, **kwargs: object) -> int: ...
