# DO NOT MANUALLY EDIT THIS FILE!
# This file was automatically generated by `nox -s generate-stubs`

from autocv._about import (
    __author__ as __author__,
)
from autocv._about import (
    __ci__ as __ci__,
)
from autocv._about import (
    __copyright__ as __copyright__,
)
from autocv._about import (
    __docs__ as __docs__,
)
from autocv._about import (
    __email__ as __email__,
)
from autocv._about import (
    __git_sha1__ as __git_sha1__,
)
from autocv._about import (
    __issue_tracker__ as __issue_tracker__,
)
from autocv._about import (
    __license__ as __license__,
)
from autocv._about import (
    __maintainer__ as __maintainer__,
)
from autocv._about import (
    __url__ as __url__,
)
from autocv._about import (
    __version__ as __version__,
)

from .auto_color_aid import AutoColorAid as AutoColorAid
from .autocv import AutoCV as AutoCV

__all__ = [
    "AutoCV",
    "AutoColorAid",
    "__author__",
    "__ci__",
    "__copyright__",
    "__docs__",
    "__email__",
    "__git_sha1__",
    "__issue_tracker__",
    "__license__",
    "__maintainer__",
    "__url__",
    "__version__",
]
