"""Configuration file for the Sphinx documentation builder.

This file is execfile()d with the current directory set to its
containing dir.

Note that not all possible configuration values are present in this
autogenerated file.
"""

from __future__ import annotations

import os
import sys
import types
from pathlib import Path

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, str(Path(__file__).parents[1].resolve()))

os.environ.setdefault("DISABLE_MODEL_SOURCE_CHECK", "True")
os.environ.setdefault("PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK", "True")


def _install_tkinter_stub() -> None:
    """Provide a minimal tkinter stub for doc builds without Tk installed."""
    try:
        import tkinter  # noqa: F401
    except ModuleNotFoundError:
        tkinter_stub = types.ModuleType("tkinter")

        class Tk:
            pass

        class Toplevel:
            pass

        class Canvas:
            pass

        class Frame:
            pass

        class Event:
            pass

        tkinter_stub.Tk = Tk
        tkinter_stub.Toplevel = Toplevel
        tkinter_stub.Canvas = Canvas
        tkinter_stub.Frame = Frame
        tkinter_stub.Event = Event

        tkinter_stub.NW = "nw"
        tkinter_stub.BOTH = "both"
        tkinter_stub.YES = True

        ttk_stub = types.ModuleType("tkinter.ttk")
        tkinter_stub.ttk = ttk_stub

        sys.modules.setdefault("tkinter", tkinter_stub)
        sys.modules.setdefault("tkinter.ttk", ttk_stub)


_install_tkinter_stub()

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
]
html_theme = "furo"

autodoc_member_order = "bysource"
toc_object_entries_show_parents = "hide"

# Links used for cross-referencing stuff in other documentation
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pillow": ("https://pillow.readthedocs.io/en/stable/", None),
}


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "autocv"
copyright = "2026, Zach"
author = "Zach"
release = "1.0.0"

# List of patterns, relative to docs directory, that match files and
# directories to ignore when looking for docs files.
exclude_patterns = ["_build"]

autodoc_mock_imports = [
    "antigcp",
    "PIL.ImageTk",
    "sv_ttk",
    "win32api",
    "win32con",
    "win32gui",
    "win32ui",
]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
html_theme_options = {
    "source_repository": "https://github.com/mohanz1/autocv",
    "source_branch": "main",
    "source_directory": "docs/",
}

html_static_path = ["_static"]
