"""Configuration file for the Sphinx documentation builder.

This file is execfile()d with the current directory set to its
containing dir.

Note that not all possible configuration values are present in this
autogenerated file.
"""

import sys
from pathlib import Path

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, str(Path(__file__).parents[1].resolve()))


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
]
html_theme = "furo"

autodoc_member_order = "bysource"
toc_object_entries_show_parents = "hide"

# Links used for cross-referencing stuff in other documentation
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pillow": ("https://pillow.readthedocs.io/en/stable/", None),
}


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "autocv"
copyright = "2024, Zach"  # noqa: A001
author = "Zach"
release = "1.0.0"

# List of patterns, relative to docs directory, that match files and
# directories to ignore when looking for docs files.
exclude_patterns = ["_build"]

autodoc_mock_imports = ["autocv.antigcp"]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
html_theme_options = {
    "source_repository": "https://github.com/mohanz1/autocv",
    "source_branch": "main",
    "source_directory": "docs/",
}

html_static_path = ["_static"]
