name: docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: |
          poetry install --with docs --no-interaction --no-root

      - name: Sphinx build
        run: |
          cd docs
          poetry run sphinx-build -b html -j auto -a -T -W --keep-going . _build/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true