name: lint

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry
        shell: bash

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install project
        run: poetry install --with dev --no-interaction --no-root

      - name: Run ruff format
        if: always()
        run: poetry run ruff format --preview --check .

      - name: Run ruff check
        if: always()
        run: poetry run ruff check --preview --output-format=github .

      - name: Run mypy
        if: always()
        run: poetry run mypy --check .

      - name: Ensure Pipx Paths
        run: pipx ensurepath

  ci-done:
    needs: [lint]
    if: always() && !cancelled()

    runs-on: ubuntu-latest

    steps:
      - name: Set status based on required jobs
        env:
          RESULTS: ${{ join(needs.*.result, ' ') }}
        run: |
          for result in $RESULTS; do
            if [ "$result" != "success" ]; then
              exit 1
            fi
          done